Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [1]:
#%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [5]:
array_50 = np.random.randint(10,99,50)
array_50 

array([11, 70, 97, 88, 56, 20, 53, 57, 38, 39, 56, 44, 81, 94, 98, 13, 40,
       23, 72, 80, 52, 65, 68, 30, 64, 64, 95, 54, 63, 51, 49, 82, 13, 95,
       13, 28, 29, 15, 30, 50, 44, 26, 39, 72, 30, 51, 43, 78, 39, 23])

In [8]:
array_50[5::5]

array([20, 56, 13, 52, 64, 49, 28, 44, 51])

In [13]:
#2·
array_30 = np.arange(1,21)           #con valores secuenciales
array_30

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
array_30[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
array_2D =  np.random.rand(4,6,dtype=float)   #No se puede hacer de esta manera
array_2D

TypeError: rand() got an unexpected keyword argument 'dtype'

In [25]:
#3.
array_2D =  np.random.rand(4,6)+5   #4 filas de 6 elementos
     
array_2D                            # le sumamos 10 por que pedia no estar entre valor 0-1

array([[5.21652842, 5.49605157, 5.98623565, 5.38862502, 5.53381425,
        5.51826277],
       [5.19057418, 5.91798245, 5.39404707, 5.66414209, 5.46230196,
        5.62105957],
       [5.04069697, 5.43535422, 5.046279  , 5.00378091, 5.01448155,
        5.76048502],
       [5.9169376 , 5.72858349, 5.53505678, 5.1230345 , 5.41099394,
        5.88498005]])

In [36]:
array_2D[3]     
#array_2D[-1]               

array([5.9169376 , 5.72858349, 5.53505678, 5.1230345 , 5.41099394,
       5.88498005])

In [38]:
redondeado_array = np.round(array_2D[3], 2)
redondeado_array

array([5.92, 5.73, 5.54, 5.12, 5.41, 5.88])

In [58]:

#BONUS:Crea un array 3D de forma (2, 3, 5) y 30 elementos con númerosenteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos enposiciones múltiplos de 3 por 0.


array_3D = np.random.randint(0, 100,(2, 3, 5))
array_3D

array([[[91, 34, 47, 12,  0],
        [52, 30, 39, 39, 19],
        [31, 53, 15, 41, 87]],

       [[55, 15, 84, 42, 88],
        [ 9, 16, 21, 24, 92],
        [70, 60, 91, 13, 77]]])

In [56]:
array_3D.size

30